### ISSUE TITLE
Request - Custom status message

### ISSUE THREAD

**Issue by 18O4** [Reavert/VisualStudioDiscordRPC#29]
Rather than limiting the user to "File \<file name with extension>" or "Project \<project name>" in settings menu, I believe it should be possible to set your own status message along with adding "variables", such as "{file_name}" or "{extension}" to display. Below are images of what it could look like (screenshots from a VSCode extension settings of "DIscord Rich Presence" by leonardssh).

![9146_1672011817](https://user-images.githubusercontent.com/64557095/209484757-f63b8b8a-1f39-4840-aab1-ccd3ae830659.png)
![1026_1672011834](https://user-images.githubusercontent.com/64557095/209484761-c35bd1df-6f7b-411e-aac0-2faad6e64a0d.png)
![1716_1672011826](https://user-images.githubusercontent.com/64557095/209484764-c092ebc9-ba47-470e-a19b-c3cbdf2b4025.png)

**Comment by Reavert** [comment]
Implemented in 1.6.0
