### ISSUE TITLE
Discord doesn't detect

### ISSUE THREAD

**Issue by MathieDev** [Reavert/VisualStudioDiscordRPC#33]
I know there is already an issue open but I've tried all solutions people have said in there and none of them seem to work. Help would be very much appreciated !

**Comment by Ryavell** [comment]
Is this problem still relevant?

**Comment by Reavert** [comment]
Do you have any logs or message boxes? Is there a button with extension settings in the "Extensions" menu?
Did you try to start Discord with admin rights?

**Comment by kyoudari** [comment]
> Do you have any logs or message boxes? Is there a button with extension settings in the "Extensions" menu? Did you try to start Discord with admin rights?

yes, i tried to run discord as admin  but it doesn't work.

**Comment by kyoudari** [comment]
![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/137518143/b7e7580f-3ba8-4262-b619-3043f31323f6)

**Comment by kyoudari** [comment]
![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/137518143/bdfd1911-5eb4-4732-8c2e-84a90ccff49f)

**Comment by kyoudari** [comment]
![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/137518143/ce5dcfe6-e77d-428a-98a7-40d3cd875195)

**Comment by Reavert** [comment]
According to your screenshots, you have added Microsoft Visual Studio to the list of "Registered Games" in Discord.
Try to remove the app from the "Registered games" in Discord.
![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/55898777/0c030241-eaf4-4bd9-9566-565b8438e368)

**Comment by kyoudari** [comment]
> According to your screenshots, you have added Microsoft Visual Studio to the list of "Registered Games" in Discord.
> Try to remove the app from the "Registered games" in Discord.

did but still doesn't work

**Comment by Reavert** [comment]
Try also running Visual Studio with administrator rights. It usually helps.
The extension should work properly if you have not get any error/warning messages when extension starts.
In another case, I have no more ideas why the extension might not work :(

**Comment by kyoudari** [comment]
oh wow started working tysm<3
