### ISSUE TITLE
No active file/project

### ISSUE THREAD

**Issue by keytrap-x86** [Reavert/VisualStudioDiscordRPC#36]
Hi, it's not working (it used to do before) for me :

![Capture d'écran 2023-04-16 190135](https://user-images.githubusercontent.com/17864005/232328507-b09d65e1-cb84-42a5-8ce4-85fd570f561b.png)

![image](https://user-images.githubusercontent.com/17864005/232328434-ef8aeeac-992e-40db-8026-f73865e282fc.png)

**Comment by Ryavell** [comment]
Hi!
Can you tell me more about what doesn't work? 
And what result did you expect?

**Comment by toonaii** [comment]
Okay after further investigations, It seems that the problem appears only the first time visual studio is loaded.
If you close the solution without quitter VS and reopen, it works.

**Comment by Ryavell** [comment]
It looks like Visual Studio opens the file faster than the extension is initialized. Thus, the first file opening event does not reach the handler.

**Comment by toonaii** [comment]
Ohhh actually I just changed my PC and it's literally a beast and it's blazing fast so maybe it's too fast lol? :)

**Comment by Reavert** [comment]
Fixed in 1.6.0
