### ISSUE TITLE
Don't reset the VS 2022 elapsed time to 0 hours after 24 hours

### ISSUE THREAD

**Issue by ClaudiuHBann** [Reavert/VisualStudioDiscordRPC#38]
When the elapsed time within Visual Studio 2022 reaches 24 hours, the elapsed time resets back to 0 hours.
Can there be a setting or just by default where the elapsed time never resets?

**Comment by Reavert** [comment]
If you want the timer to never reset, then a mode called "WithinApplicationTimerSlot" may suit you
In this mode, the timer is set when the application starts and is never reset (for the duration of the Visual Stuido application).

Perhaps resetting the timer after 24 hours is more related to the Discord bug.

I haven't had to work in Visual Studio for more than 24 hours yet :) 
Therefore, I did not check how the extension behaves in this case.

**Comment by ClaudiuHBann** [comment]
I saw some pictures online where multiple people were in a call for more than 24 hours but I didn't saw anything related to apps, maybe it's a Discord thing idk.
