### ISSUE TITLE
Extension doesn't seem to load.

### ISSUE THREAD

**Issue by NotserpIsHere** [Reavert/VisualStudioDiscordRPC#40]
Hello, i got issue with extension not loading. Before it worked good but some day it stopped for no reason, and i don't know what. 

![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/139016287/98145ec9-3675-4e7c-bb4a-6399c041f011)
![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/139016287/f6f3b75b-1e5a-4bc2-9ba5-31791353a014)
![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/139016287/428fba4c-dae9-40cd-b621-b1d81d1b126d)

**Comment by Reavert** [comment]
Hi.
Have you try any solutions from the issues #12 and #33. There was a similar trouble.
Most often it helps to run Visual Studio with administrator rights.
Sometimes a simple restart of applications (Discord, VisualStudio) helps.

**Comment by NotserpIsHere** [comment]
i tried running visual studio with administrator, but it didnt give any results, i restarted dc/vs 2022 many times but didnt work too. like extension worked normally but now stopped working for no reason.

**Comment by Reavert** [comment]
It is very strange indeed.

Try to check the Visual Studio startup log file (_ActivityLog.xml_ or _ActivityLog.Setup.xml_)

These files are located in the following path:
_%AppData%\Microsoft\VisualStudio\\<YourVisualStudioVersion\>_

Try to find something there about the extension startup.

Did you try to reinstall the extension?

**Comment by NotserpIsHere** [comment]
i tried reinstall it, and there is anything wrong in activitylogs

**Comment by Reavert** [comment]
Can you attach the error log?
