### ISSUE TITLE
Extension throws error when starting Visual Studio

### ISSUE THREAD

**Issue by 1nade** [Reavert/VisualStudioDiscordRPC#43]
Extension fails to load when starting Visual Studio.

Here's the ActivityLog:
[ActivityLog.xml.txt](https://github.com/Reavert/VisualStudioDiscordRPC/files/12876773/ActivityLog.xml.txt)

**Comment by 1nade** [comment]
Also throws this error when starting Visual Studio:

![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/36055611/81084e7d-6474-4783-b357-a8f7de9ad5a6)

**Comment by Reavert** [comment]
Perhaps this is due to a change in the storage location of the settings.
Can you also attach a file that is located at %LocalAppData%/VisualStudioDiscordRPC/settings.json?
I would like to make sure that everything is fine with the settings.

**Comment by Zagrthos** [comment]
I attach mine too, thanks for the extension btw 🙂 
[settings.json](https://github.com/Reavert/VisualStudioDiscordRPC/files/12887501/settings.json)

**Comment by Reavert** [comment]
@Zagrthos I found the reason of your error.
To fix that, replace:
"StatePlug": "None**Asset**Plug", 
to:
"StatePlug": "None**Text**Plug",

**Comment by Reavert** [comment]
But it seems to me that @1nade has another problem. 
I'm still figuring out your problem, but if this fix or upgrade to 1.6.1 helps you too, please let me know.

**Comment by Zagrthos** [comment]
Installing the new update solved it, thanks!

**Comment by Reavert** [comment]
@1nade Is your error still actual after the installing 1.6.1 extension patch?

**Comment by 1nade** [comment]
yeah, same error and everything

**Comment by Cappuccino093** [comment]
I'm having the same problem, here is my `settings.json`:

```json
{
  "RichPresenceEnabled": true,
  "Language": "English",
  "LargeIconPlug": "ExtensionIconPlug",
  "SmallIconPlug": "VisualStudioVersionIconPlug",
  "DetailsPlug": "FileNameTextPlug",
  "StatePlug": "SolutionNameTextPlug",
  "TimerPlug": "FileScopeTimerPlug",
  "FirstButtonPlug": "GitRepositoryButtonPlug",
  "SecondButtonPlug": "NoneTextPlug",
  "ApplicationID": "914622396630175855",
  "UpdateTimeout": 1000,
  "Version": "1.0.0",
  "UpdateNotifications": true,
  "TranslationsPath": "Translations/"
}
```

**Comment by Cappuccino093** [comment]
So, the extension was updated recently and looks that the error was resolved, thank you!

**Comment by 1nade** [comment]
> Attach, please, your settings file (%LocalAppData%/VisualStudioDiscordRPC/settings.json)

here you go:
[settings.json](https://github.com/Reavert/VisualStudioDiscordRPC/files/13048053/settings.json)

**Comment by Reavert** [comment]
Strange. The file is filled with Null only.
Then I will add processing soon, in case the settings file gets corrupted.

**Comment by 1nade** [comment]
i have vs 2022 enterprise, let me try to install it on community

**Comment by 1nade** [comment]
> Is this the first time you installed an extension? Or did you have it installed before and you used it, and then updated and everything broke?

it fixed itself after i reinstalled windows, i guess it was just a bug with my pc 🤷 thank you for helping
