### ISSUE TITLE
Extension fails to load if repository URL is SSH based

### ISSUE THREAD

**Issue by MoonieGZ** [Reavert/VisualStudioDiscordRPC#46]
Heya, I got an error when loading my project recently.

![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/1693101/ef3b1fe4-bb7d-4165-b7f0-22c7b01c17d1)

Found it was due to my repository having a `git@github.com:[username]/[repository].git` format.

Unloading the project, unchecking the button in settings and reloading the project fixed it. If you don't unload the project first, you get this error:

![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/1693101/47a14b2f-f042-4b0f-af5e-7130b4816918)

Hopefully that helps you in the future if other people have the issue! Love the project 👍

**Comment by Reavert** [comment]
Hi!
I have added validation for the repository URL. It should work without errors in version 1.6.4.
But the button will not be displayed for repositories with URLs that use SSH format, because Discord Rich Presence requires an http/https link.
