### ISSUE TITLE
Repository Button dont want to give me the link

### ISSUE THREAD

**Issue by CelinaxCute** [Reavert/VisualStudioDiscordRPC#52]
Repository button do nothing

**Comment by Reavert** [comment]
Hi.
I checked that the link for the buttons is set and it's OK. The buttons should have worked. 🤔 
But I noticed that the buttons currently don't work at all for any applications using Discord RPC. 
Most likely, the error is on the Discord side.
I think we just need to wait a bit until Discord fixes its problems.

**Comment by Reavert** [comment]
Discord has just been updated. I checked the functionality of the buttons - now the buttons are working
