### ISSUE TITLE
Multiple instances not detected anymore

### ISSUE THREAD

**Issue by ferfnin** [Reavert/VisualStudioDiscordRPC#56]
I think discord changed something on how activities work, previously if i had multiple Visual Studio 22 running it would show all of them on my profile, but now it shows only one.

I download your source modified the version and installed it together the version from market place and its now detecting two Visual Studios instead of just one.

I work with c++ i have little to no experience with c# or vs extensions, Isn't possible to tweak it somehow to still detect all running instances?

[`public const string DefaultApplicationId = "914622396630175855";`](https://github.com/Reavert/VisualStudioDiscordRPC/blob/1ad94098cebc5c1297cfc4ea8f8cd19fa95926f5/VisualStudioDiscordRPC.Shared/DiscordRpcController.cs#L14)
This id is the one from the discord developer website? when you create a custom app.

-Edit-
Yes its, one way I thought to achieve it was to create multiple copies of the same app and pick one Id for each instance of Visual Studio, but i wonder if there's any better approach.

**Comment by Reavert** [comment]
There has already been a similar issue #55.
Your issue is only related to the Visual Studio DIscord RPC extension? Or other extensions have the same trouble?

**Comment by ferfnin** [comment]
> There has already been a similar issue #55. Your issue is only related to the Visual Studio DIscord RPC extension? Or other extensions have the same trouble?

Yes i only use Visual Studio

**Comment by Reavert** [comment]
I didn't do anything to disable the visibility of multiple instances. 
Most likely, this is a Discord bug or a new feature of the client's frontend, (because when you close one instance, the second one will be displayed)
Also, I didn't find anything in the app settings on the Discord Developer Portal to change this somehow.

**Comment by ferfnin** [comment]
Can you add me on discord? my id: c.e.sar
